#!/usr/bin/env bash
#
# restore-runbook.sh — generate a detailed, self-contained restore runbook.
#
# Introspects the CURRENT backup set in S3 (latest snapshots of each type) plus
# the effective configuration, and writes RESTORE.md to the backup folder root
# ($PREFIX/RESTORE.md). The runbook takes an operator from an EMPTY machine to a
# fully-functioning self-hosted Supabase, covering: prerequisites, logical quick
# restore, point-in-time recovery, storage re-hydration, the pgsodium key,
# secrets, and a verification checklist.
#
# Regenerated at the end of every backup cycle (see lib.sh update_runbook) so the
# document always reflects the newest available snapshots. Safe to run manually:
#   entrypoint.sh gen-runbook
#
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export LOG_TAG="runbook"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"
require_backup_target

# The image used in the copy-pasteable restore commands. Override with
# RESTORE_IMAGE if you republish under a different name/tag.
: "${RESTORE_IMAGE:=ghcr.io/corelix-io/coolify-enhanced-templates/supabase-backup:15}"

EXT="$(enc_ext)"

# --- gather current inventory ---------------------------------------------- #
latest_of() { s3_list "$1" | sed 's#/$##' | grep -E '^[0-9]{8}T[0-9]{6}Z$' | sort -r | head -n1; }
# Extract a JSON field (quoted or bare) from a single-line manifest on stdin.
json_field() { sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\?\([^\",}]*\)\"\?.*/\1/p" | head -n1; }

SNAP_LOGICAL="$(latest_of logical || true)"
SNAP_BASE="$(latest_of basebackups || true)"
SNAP_STORAGE="$(latest_of storage || true)"
SNAP_CONFIG="$(latest_of config || true)"
WAL_COUNT="$(s3_list wal | grep -c . || true)"; : "${WAL_COUNT:=0}"

lman="$(s3_get_stream "logical/${SNAP_LOGICAL}/manifest.json" 2>/dev/null || true)"
PG_VERSION="$(printf '%s' "$lman" | json_field pg_version || true)";   : "${PG_VERSION:=unknown}"
DATABASES="$(printf '%s' "$lman"  | json_field databases  || true)";   [[ -n "$DATABASES" ]] || DATABASES="$BACKUP_DATABASES"
SOURCE_IMAGE="$(printf '%s' "$lman" | json_field source_image || true)"; [[ -n "$SOURCE_IMAGE" ]] || SOURCE_IMAGE="$SOURCE_IMAGE_TAG"

bman="$(s3_get_stream "basebackups/${SNAP_BASE}/manifest.json" 2>/dev/null || true)"
BASE_LSN="$(printf '%s' "$bman" | json_field start_lsn || true)"; : "${BASE_LSN:=unknown}"

cman="$(s3_get_stream "config/${SNAP_CONFIG}/manifest.json" 2>/dev/null || true)"
DBCONFIG_CAPTURED="$(printf '%s' "$cman" | json_field dbconfig_captured || true)"; : "${DBCONFIG_CAPTURED:=false}"

sman="$(s3_get_stream "storage/${SNAP_STORAGE}/manifest.json" 2>/dev/null || true)"
STORAGE_OBJECTS="$(printf '%s' "$sman" | json_field object_count || true)"; : "${STORAGE_OBJECTS:=unknown}"

DB1="${DATABASES%%[, ]*}"; : "${DB1:=postgres}"
PG_MAJOR="$(printf '%s' "$PG_VERSION" | sed -n 's/^\([0-9]\+\).*/\1/p')"; : "${PG_MAJOR:=15}"

# Human-friendly "(none yet)" for empty snapshots.
show() { [[ -n "$1" ]] && printf '%s' "$1" || printf '(none yet)'; }

log "generating RESTORE.md (logical=${SNAP_LOGICAL:-none} base=${SNAP_BASE:-none} wal=${WAL_COUNT} storage=${SNAP_STORAGE:-none} config=${SNAP_CONFIG:-none})"

# --- render (quoted heredoc = fully literal; tokens replaced below) --------- #
TMPL="$(cat <<'MD'
# Supabase Disaster-Recovery Runbook

> **Auto-generated by the Corelix Supabase backup sidecar — do not edit by hand.**
> Regenerated at the end of every backup cycle. It reflects the newest snapshots
> available at generation time (`@@GENERATED@@`).

This document takes you from a **blank machine** to a **fully-functioning
self-hosted Supabase**, using only this backup bucket and your offline
encryption key. Read it top to bottom before starting a real restore.

---

## 0. What is in this backup

| Surface | Latest snapshot | Notes |
|---|---|---|
| Logical DB dump | `@@SNAP_LOGICAL@@` | databases: `@@DATABASES@@`, PostgreSQL `@@PG_VERSION@@` |
| Physical base (PITR) | `@@SNAP_BASE@@` | start_lsn `@@BASE_LSN@@` |
| WAL archive (PITR) | `@@WAL_COUNT@@ segment(s)` | continuous, under `wal/` |
| Storage objects | `@@SNAP_STORAGE@@` | ~`@@STORAGE_OBJECTS@@` object(s) |
| DB config / pgsodium | `@@SNAP_CONFIG@@` | pgsodium key captured: **@@DBCONFIG_CAPTURED@@** |

- **Backup target:** `@@ENDPOINT@@`  bucket `@@BUCKET@@`  prefix `@@PREFIX@@`  (region `@@REGION@@`, path-style `@@PATHSTYLE@@`)
- **Encryption:** `@@ENCRYPTION@@`  (age recipient: `@@AGE_RECIPIENT@@`)
- **Source Supabase image:** `@@SOURCE_IMAGE@@`  →  restore with **postgres major @@PG_MAJOR@@**.

Two recovery options:
- **Path A — Logical restore** (simplest; RPO = last dump interval). Best for
  "the database is gone / corrupted, give me the last good copy."
- **Path B — Point-in-time recovery** (minimum loss; RPO ≈ seconds). Best for
  "restore to just before 03:14 UTC when the bad migration ran."

---

## 1. Prerequisites (gather these first)

1. **A fresh host** with Docker + Docker Compose (and Coolify, if you deploy
   Supabase through it — recommended).
2. **The age private key** that matches the recipient above
   (`@@AGE_RECIPIENT@@`). Without it NOTHING here can be decrypted. You created
   it with `age-keygen`; the private file looks like `AGE-SECRET-KEY-1...`.
   Put it on the new host, e.g. `/root/keys/age.key` (chmod 600).
3. **This backup image:** `@@IMAGE@@` (it contains the matching `pg_*` client
   tools and the restore scripts).
4. **Read access to this bucket** — the same `BACKUP_S3_*` credentials the
   backup used (or a read-only equivalent).
5. **Your Supabase secrets** (see §5) — they are NOT in any backup by design.

Export the target coordinates once (reused by every command below):

```bash
export BACKUP_S3_ENDPOINT='@@ENDPOINT@@'
export BACKUP_S3_BUCKET='@@BUCKET@@'
export BACKUP_S3_REGION='@@REGION@@'
export BACKUP_S3_FORCE_PATH_STYLE='@@PATHSTYLE@@'
export BACKUP_PREFIX='@@PREFIX@@'
export BACKUP_ENCRYPTION='@@ENCRYPTION@@'
export BACKUP_S3_ACCESS_KEY='<your backup S3 access key>'
export BACKUP_S3_SECRET_KEY='<your backup S3 secret key>'
# read-only key used ONLY to decrypt during restore:
export AGE_KEY_HOST_PATH='/root/keys/age.key'
```

Sanity-check connectivity + decryption before you rely on it:

```bash
docker run --rm \
  -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \
  -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \
  -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \
  -e PGPASSWORD=unused \
  @@IMAGE@@ preflight
```

---

## 2. Bring up an empty Supabase

Deploy a **new, empty** Supabase stack the same way you originally did (Coolify →
New Resource → Supabase, or your compose). Use the **same major Postgres
version (@@PG_MAJOR@@)** and, ideally, the same image `@@SOURCE_IMAGE@@`.

- For **Path A (logical)** you can let Supabase initialise normally, then we
  overwrite the target database.
- For **Path B (PITR)** you will STOP the Postgres container and replace its data
  directory (see §4), so bring the stack up once to create volumes, then stop db.

Note the Docker **network** name of the Supabase stack and the **db host**
(usually `supabase-db`). You will attach the restore container to that network.

---

## 3. Path A — Logical restore (simplest)

Restores roles → recreates `@@DB1@@` from `template0` → `pg_restore`. Handles the
`supabase_admin` ownership gotcha automatically.

```bash
docker run --rm -it \
  --network '<supabase-stack-network>' \
  -e PGHOST='supabase-db' -e PGPORT=5432 -e PGUSER='supabase_admin' \
  -e PGPASSWORD='<your SERVICE_PASSWORD_POSTGRES>' \
  -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \
  -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \
  -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \
  -e BACKUP_ENCRYPTION -e BACKUP_AGE_IDENTITY_FILE=/keys/age.key \
  -e RESTORE_CONFIRM=yes \
  -v "${AGE_KEY_HOST_PATH}:/keys/age.key:ro" \
  @@IMAGE@@ restore-logical @@SNAP_LOGICAL@@ @@DB1@@
```

- Omit the snapshot arg to use the latest automatically.
- Repeat for each database in `@@DATABASES@@` (change the last argument).
- The script prints a user-table count at the end as a sanity check.

Then continue with §5 (secrets), §6 (pgsodium key) and §7 (storage).

---

## 4. Path B — Point-in-time recovery (minimum loss)

Replays the physical base + archived WAL up to an exact instant. Runs against a
**stopped** Postgres with an **empty** data directory.

1. **Stop** the Supabase `db` container and empty its data volume (the restore
   refuses to write into a non-empty datadir).
2. **Prepare the datadir** — fetch + extract the base, write recovery config:

   ```bash
   docker run --rm -it \
     -e PGPASSWORD=unused \
     -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \
     -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \
     -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \
     -e BACKUP_ENCRYPTION -e BACKUP_AGE_IDENTITY_FILE=/keys/age.key \
     -e RESTORE_CONFIRM=yes \
     -v "${AGE_KEY_HOST_PATH}:/keys/age.key:ro" \
     -v '<supabase-db-data-volume>:/var/lib/postgresql/data' \
     @@IMAGE@@ restore-pitr \
       --target-time '2026-01-01 03:14:00+00' \
       --base @@SNAP_BASE@@ \
       --datadir /var/lib/postgresql/data
   ```

   (Omit `--base` to use the latest base `@@SNAP_BASE@@`.)
3. Ensure the datadir is owned by the Supabase postgres uid/gid, and make WAL
   fetch available to Postgres. The script prints exact `chown` + start steps.
4. **Start** Postgres. It replays WAL to the target time and promotes itself.
   Recovery ends when the archived WAL is exhausted (`wal-fetch` returns 1).
5. Continue with §5, §6, §7.

> The restore tools MUST be postgres major **@@PG_MAJOR@@** to read this base.

---

## 5. Restore secrets into Coolify env

These are **never** stored in backups. Copy them back into the new stack's
environment (Coolify → the Supabase resource → Environment Variables). The names
you must supply are listed in `config/@@SNAP_CONFIG@@/secrets.manifest.json`:

- `JWT_SECRET`, `ANON_KEY`, `SERVICE_ROLE_KEY`, `SECRET_KEY_BASE`
- `SERVICE_PASSWORD_POSTGRES`, `SERVICE_USER_MINIO`, `SERVICE_PASSWORD_MINIO`
- `DASHBOARD_USERNAME`, `DASHBOARD_PASSWORD`

If you lost these, JWTs and API keys will not match the restored data — you can
rotate them, but existing signed tokens become invalid.

---

## 6. Re-apply the pgsodium / Vault key

@@CONFIG_SECTION@@

---

## 7. Re-hydrate Storage objects into MinIO

The database only holds object *metadata*; the bytes live in MinIO. Restore them
from the latest `storage/` snapshot (~@@STORAGE_OBJECTS@@ objects):

```bash
# 1) download + decrypt the storage archive to a local dir
docker run --rm -it \
  -e PGPASSWORD=unused \
  -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \
  -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \
  -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \
  -e BACKUP_ENCRYPTION -e BACKUP_AGE_IDENTITY_FILE=/keys/age.key \
  -v "${AGE_KEY_HOST_PATH}:/keys/age.key:ro" \
  -v "$PWD/storage-restore:/out" \
  @@IMAGE@@ bash -lc \
    'source /scripts/lib.sh; s3_get_stream "storage/@@SNAP_STORAGE@@/storage.tar.gz@@EXT@@" | decrypt_stream | tar -C /out -xzf -'

# 2) push the objects back into the NEW MinIO with mc or rclone, e.g.:
#    rclone sync ./storage-restore  minio:<STORAGE_BUCKET>
```

Point `MINIO_*` at the new stack's MinIO. Verify object counts match (~@@STORAGE_OBJECTS@@).

---

## 8. Verification checklist

- [ ] `restore-logical` printed a non-zero user-table count for `@@DB1@@`.
- [ ] `auth.users` row count looks right (`select count(*) from auth.users;`).
- [ ] Supabase Studio loads and login works (secrets §5 correct).
- [ ] A row with an encrypted/Vault column decrypts (pgsodium key §6 correct).
- [ ] A previously-uploaded file downloads from Storage (§7 correct).
- [ ] `select pg_is_in_recovery();` returns `f` (PITR promoted) — Path B only.

If every box is checked, the restore is complete.

---

## 9. Verifying backups (without a full restore)

The scheduled `verify` job runs a **structural** check by default — it confirms
each object exists, is non-trivially sized, and (for age) starts with a valid age
header. It does **not** decrypt, because the backup box only holds the age
**public** key. That is by design: a compromised backup host cannot read your data.

To validate a backup **end-to-end** (decrypt + `pg_restore --list`) periodically,
run `verify` in a one-off container **with the private key mounted** — on a trusted
machine, never by leaving the key on the always-on backup service:

```bash
docker run --rm \
  -e PGPASSWORD=unused \
  -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \
  -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \
  -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \
  -e BACKUP_ENCRYPTION -e BACKUP_AGE_IDENTITY_FILE=/keys/age.key \
  -e VERIFY_DECRYPT=true \
  -v "${AGE_KEY_HOST_PATH}:/keys/age.key:ro" \
  @@IMAGE@@ verify
```

Add `-e VERIFY_FULL=true -e VERIFY_PGHOST=<scratch-db-host>` to also test-restore
into a throwaway database and count tables.

---

*Generated `@@GENERATED@@` — prefix `@@PREFIX@@` — image `@@IMAGE@@`.*
MD
)"

# Build the pgsodium section conditionally (was the key captured?).
if [[ "$DBCONFIG_CAPTURED" == "true" ]]; then
  CONFIG_SECTION="The pgsodium root key WAS captured (db-config mounted). Restore it:

\`\`\`bash
# download + decrypt the db-config archive, then copy the key files into the
# new db's config volume (e.g. /etc/postgresql-custom) BEFORE first real use.
docker run --rm -it \\
  -e PGPASSWORD=unused \\
  -e BACKUP_S3_ENDPOINT -e BACKUP_S3_BUCKET -e BACKUP_S3_REGION \\
  -e BACKUP_S3_FORCE_PATH_STYLE -e BACKUP_PREFIX \\
  -e BACKUP_S3_ACCESS_KEY -e BACKUP_S3_SECRET_KEY \\
  -e BACKUP_ENCRYPTION -e BACKUP_AGE_IDENTITY_FILE=/keys/age.key \\
  -v \"\${AGE_KEY_HOST_PATH}:/keys/age.key:ro\" \\
  -v \"\$PWD/dbconfig-restore:/out\" \\
  @@IMAGE@@ bash -lc \\
    'source /scripts/lib.sh; s3_get_stream \"config/@@SNAP_CONFIG@@/db-config.tar.gz@@EXT@@\" | decrypt_stream | tar -C /out -xzf -'
\`\`\`

Then place the extracted key material into the new Supabase db-config volume and
restart Postgres so pgsodium/Vault can decrypt existing columns."
else
  CONFIG_SECTION="> **WARNING — the pgsodium key was NOT captured** (db-config volume was not
> mounted at backup time). Any pgsodium/Vault-**encrypted columns cannot be
> decrypted** after this restore. To fix for future backups, mount the
> \`supabase-db-config\` volume read-only into the backup container (see the
> template's commented \`/dbconfig\` mount). Non-encrypted data restores fine."
fi

# Token substitution (bash param expansion = metachar-safe, no sed escaping).
# CONFIG_SECTION is injected FIRST because it embeds @@IMAGE@@/@@SNAP_CONFIG@@/
# @@EXT@@ tokens that the later global replacements must still resolve.
OUT="$TMPL"
OUT="${OUT//@@CONFIG_SECTION@@/$CONFIG_SECTION}"
OUT="${OUT//@@EXT@@/$EXT}"
OUT="${OUT//@@GENERATED@@/$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
OUT="${OUT//@@PREFIX@@/$BACKUP_PREFIX}"
OUT="${OUT//@@ENDPOINT@@/$BACKUP_S3_ENDPOINT}"
OUT="${OUT//@@BUCKET@@/$BACKUP_S3_BUCKET}"
OUT="${OUT//@@REGION@@/$BACKUP_S3_REGION}"
OUT="${OUT//@@PATHSTYLE@@/$BACKUP_S3_FORCE_PATH_STYLE}"
OUT="${OUT//@@ENCRYPTION@@/$BACKUP_ENCRYPTION}"
OUT="${OUT//@@AGE_RECIPIENT@@/${BACKUP_AGE_RECIPIENT:-(n/a)}}"
OUT="${OUT//@@IMAGE@@/$RESTORE_IMAGE}"
OUT="${OUT//@@PG_VERSION@@/$PG_VERSION}"
OUT="${OUT//@@PG_MAJOR@@/$PG_MAJOR}"
OUT="${OUT//@@SOURCE_IMAGE@@/$SOURCE_IMAGE}"
OUT="${OUT//@@DATABASES@@/$DATABASES}"
OUT="${OUT//@@DB1@@/$DB1}"
OUT="${OUT//@@SNAP_LOGICAL@@/$(show "$SNAP_LOGICAL")}"
OUT="${OUT//@@SNAP_BASE@@/$(show "$SNAP_BASE")}"
OUT="${OUT//@@BASE_LSN@@/$BASE_LSN}"
OUT="${OUT//@@WAL_COUNT@@/$WAL_COUNT}"
OUT="${OUT//@@SNAP_STORAGE@@/$(show "$SNAP_STORAGE")}"
OUT="${OUT//@@STORAGE_OBJECTS@@/$STORAGE_OBJECTS}"
OUT="${OUT//@@SNAP_CONFIG@@/$(show "$SNAP_CONFIG")}"
OUT="${OUT//@@DBCONFIG_CAPTURED@@/$DBCONFIG_CAPTURED}"

# Write to a temp file and upload to the backup folder root as RESTORE.md.
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT
printf '%s\n' "$OUT" > "$TMPFILE"

s3_put_file "$TMPFILE" "RESTORE.md"
log "RESTORE.md written -> $(s3_path RESTORE.md) ($(human_bytes "$(wc -c < "$TMPFILE")"))"
